name: daily_notes
description: An intuitive app to save your ideas.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  flutter_markdown: ^0.6.15
  go_router: ^8.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
